import { useState } from 'react'
import { useLocation } from 'react-router-dom'
import './module-page.css'

type Row = Record<string, string>
type ModuleConfig = { title: string; description: string; singular: string; columns: { key: string; label: string }[]; rows: Row[]; metrics?: { label: string; value: string }[] }

const moduleData: Record<string, ModuleConfig> = {
  empresa: { title: 'Empresa', description: 'Información corporativa y configuración del negocio.', singular: 'empresa', columns: [{ key: 'name', label: 'Razón social' }, { key: 'taxId', label: 'RUC' }, { key: 'city', label: 'Ciudad' }, { key: 'status', label: 'Estado' }], rows: [{ id: '1', name: 'Grupo Horizonte S.A.C.', taxId: '20605478129', city: 'Lima', status: 'Activa' }], metrics: [{ label: 'Sucursales', value: '5' }, { label: 'Colaboradores', value: '48' }, { label: 'Antigüedad', value: '8 años' }] },
  sucursales: { title: 'Sucursales', description: 'Administra sedes, responsables y rendimiento operativo.', singular: 'sucursal', columns: [{ key: 'name', label: 'Sucursal' }, { key: 'city', label: 'Ciudad' }, { key: 'manager', label: 'Responsable' }, { key: 'status', label: 'Estado' }], rows: [{ id: '1', name: 'Lima Centro', city: 'Lima', manager: 'Ana Torres', status: 'Activa' }, { id: '2', name: 'Arequipa', city: 'Arequipa', manager: 'Carlos Ruiz', status: 'Activa' }, { id: '3', name: 'Trujillo', city: 'Trujillo', manager: 'María León', status: 'Activa' }, { id: '4', name: 'Cusco', city: 'Cusco', manager: 'Diego Flores', status: 'En revisión' }] },
  productos: { title: 'Productos', description: 'Catálogo de productos y variables para análisis.', singular: 'producto', columns: [{ key: 'name', label: 'Producto' }, { key: 'category', label: 'Categoría' }, { key: 'price', label: 'Precio' }, { key: 'stock', label: 'Stock' }, { key: 'status', label: 'Estado' }], rows: [{ id: '1', name: 'Laptop Pro 14', category: 'Computación', price: '$ 1,249', stock: '42', status: 'Activo' }, { id: '2', name: 'Monitor UltraWide', category: 'Monitores', price: '$ 489', stock: '18', status: 'Activo' }, { id: '3', name: 'Teclado Mecánico K2', category: 'Periféricos', price: '$ 89', stock: '76', status: 'Activo' }, { id: '4', name: 'Mouse Ergonómico M1', category: 'Periféricos', price: '$ 45', stock: '9', status: 'Bajo stock' }] },
  ventas: { title: 'Ventas', description: 'Registra y consulta cantidades e importes por sucursal.', singular: 'venta', columns: [{ key: 'code', label: 'Pedido' }, { key: 'branch', label: 'Sucursal' }, { key: 'customer', label: 'Cliente' }, { key: 'amount', label: 'Importe' }, { key: 'status', label: 'Estado' }], rows: [{ id: '1', code: '#MF-9284', branch: 'Lima Centro', customer: 'TecnoRed S.A.', amount: '$ 4,280', status: 'Completada' }, { id: '2', code: '#MF-9283', branch: 'Arequipa', customer: 'Soluciones Sur', amount: '$ 1,920', status: 'Completada' }, { id: '3', code: '#MF-9282', branch: 'Trujillo', customer: 'Nexo Digital', amount: '$ 3,450', status: 'Pendiente' }] },
  inventario: { title: 'Inventario', description: 'Existencias y movimientos de productos en todas las sedes.', singular: 'movimiento', columns: [{ key: 'product', label: 'Producto' }, { key: 'branch', label: 'Sucursal' }, { key: 'quantity', label: 'Cantidad' }, { key: 'movement', label: 'Movimiento' }, { key: 'status', label: 'Estado' }], rows: [{ id: '1', product: 'Laptop Pro 14', branch: 'Lima Centro', quantity: '42', movement: 'Ingreso', status: 'Disponible' }, { id: '2', product: 'Monitor UltraWide', branch: 'Arequipa', quantity: '8', movement: 'Salida', status: 'Disponible' }, { id: '3', product: 'Mouse Ergonómico M1', branch: 'Cusco', quantity: '9', movement: 'Alerta', status: 'Bajo stock' }] },
  vectores: { title: 'Vectores', description: 'Representa información empresarial unidimensional.', singular: 'vector', columns: [{ key: 'name', label: 'Nombre' }, { key: 'values', label: 'Valores' }, { key: 'source', label: 'Origen' }, { key: 'status', label: 'Estado' }], rows: [{ id: '1', name: 'Ventas por sucursal', values: '[98420, 72180, 55640, 34890]', source: 'Ventas · septiembre', status: 'Listo' }, { id: '2', name: 'Meta mensual', values: '[120000, 90000, 70000, 50000]', source: 'Metas · septiembre', status: 'Listo' }, { id: '3', name: 'Rotación de stock', values: '[4.2, 3.8, 2.9, 3.4]', source: 'Inventario', status: 'Listo' }] },
  matrices: { title: 'Matrices', description: 'Representa información multidimensional por sucursal y producto.', singular: 'matriz', columns: [{ key: 'name', label: 'Nombre' }, { key: 'dimensions', label: 'Dimensiones' }, { key: 'source', label: 'Origen' }, { key: 'status', label: 'Estado' }], rows: [{ id: '1', name: 'Ventas por producto', dimensions: '5 × 4', source: 'Ventas · septiembre', status: 'Lista' }, { id: '2', name: 'Real vs. metas', dimensions: '5 × 4', source: 'Ventas / Metas', status: 'Lista' }, { id: '3', name: 'Inventario global', dimensions: '4 × 5', source: 'Inventario', status: 'Lista' }] },
  operaciones: { title: 'Operaciones', description: 'Ejecuta cálculos y conserva sus resultados reproducibles.', singular: 'operación', columns: [{ key: 'operation', label: 'Operación' }, { key: 'input', label: 'Entrada' }, { key: 'result', label: 'Resultado' }, { key: 'executedBy', label: 'Ejecutado por' }, { key: 'status', label: 'Estado' }], rows: [{ id: '1', operation: 'Producto escalar', input: 'Cantidades × precios', result: '$ 284,920', executedBy: 'Laura Méndez', status: 'Completada' }, { id: '2', operation: 'Resta matricial', input: 'Ventas - metas', result: '+$ 18,420', executedBy: 'Laura Méndez', status: 'Completada' }, { id: '3', operation: 'Transpuesta', input: 'Ventas por producto', result: '4 × 5', executedBy: 'Carlos Ruiz', status: 'Completada' }] },
  'combinaciones-lineales': { title: 'Combinaciones lineales', description: 'Construye indicadores ponderados de ventas, rentabilidad y rotación.', singular: 'combinación', columns: [{ key: 'name', label: 'Indicador' }, { key: 'weights', label: 'Pesos' }, { key: 'result', label: 'Resultado' }, { key: 'status', label: 'Estado' }], rows: [{ id: '1', name: 'Índice comercial', weights: 'Ventas 50% · Margen 30% · Rotación 20%', result: '87.4', status: 'Completada' }, { id: '2', name: 'Salud de inventario', weights: 'Stock 40% · Rotación 60%', result: '74.8', status: 'Completada' }] },
  historial: { title: 'Historial', description: 'Trazabilidad de cálculos, entradas, resultados y usuarios.', singular: 'registro', columns: [{ key: 'operation', label: 'Operación' }, { key: 'user', label: 'Usuario' }, { key: 'date', label: 'Fecha' }, { key: 'result', label: 'Resultado' }], rows: [{ id: '1', operation: 'Producto escalar', user: 'Laura Méndez', date: '24 sep 2026 · 10:42', result: 'Completada' }, { id: '2', operation: 'Resta matricial', user: 'Laura Méndez', date: '24 sep 2026 · 09:18', result: 'Completada' }, { id: '3', operation: 'Suma vectorial', user: 'Carlos Ruiz', date: '23 sep 2026 · 16:05', result: 'Completada' }] },
  reportes: { title: 'Reportes', description: 'Indicadores, gráficos y exportaciones empresariales.', singular: 'reporte', columns: [{ key: 'name', label: 'Reporte' }, { key: 'period', label: 'Periodo' }, { key: 'updated', label: 'Actualizado' }, { key: 'status', label: 'Estado' }], rows: [{ id: '1', name: 'Ventas por sucursal', period: 'Septiembre 2026', updated: 'Hace 12 min', status: 'Disponible' }, { id: '2', name: 'Rotación de inventario', period: 'Tercer trimestre', updated: 'Hace 1 h', status: 'Disponible' }, { id: '3', name: 'Cumplimiento de metas', period: 'Septiembre 2026', updated: 'Hace 2 h', status: 'Disponible' }] },
  usuarios: { title: 'Usuarios', description: 'Gestiona usuarios, roles y permisos de acceso.', singular: 'usuario', columns: [{ key: 'name', label: 'Usuario' }, { key: 'email', label: 'Correo' }, { key: 'role', label: 'Rol' }, { key: 'status', label: 'Estado' }], rows: [{ id: '1', name: 'Laura Méndez', email: 'laura@horizonte.pe', role: 'Administrador', status: 'Activo' }, { id: '2', name: 'Carlos Ruiz', email: 'carlos@horizonte.pe', role: 'Analista', status: 'Activo' }, { id: '3', name: 'Ana Torres', email: 'ana@horizonte.pe', role: 'Consulta', status: 'Activo' }] },
  configuracion: { title: 'Configuración', description: 'Parámetros generales de la plataforma y el espacio de trabajo.', singular: 'parámetro', columns: [{ key: 'name', label: 'Parámetro' }, { key: 'value', label: 'Valor' }, { key: 'description', label: 'Descripción' }], rows: [{ id: '1', name: 'Moneda principal', value: 'USD', description: 'Moneda para indicadores y reportes' }, { id: '2', name: 'Zona horaria', value: 'America/Lima', description: 'Zona horaria del espacio de trabajo' }, { id: '3', name: 'Decimales', value: '2', description: 'Precisión de resultados matemáticos' }] },
}

const labels: Record<string, string> = Object.fromEntries(Object.entries(moduleData).map(([key, value]) => [key, value.title]))

function statusClass(value: string) {
  const normalized = value.toLowerCase()
  if (normalized.includes('activa') || normalized.includes('activo') || normalized.includes('lista') || normalized.includes('listo') || normalized.includes('completada') || normalized.includes('disponible')) return 'status-success'
  if (normalized.includes('revisión') || normalized.includes('pendiente') || normalized.includes('alerta') || normalized.includes('bajo')) return 'status-warning'
  return ''
}

export function PlaceholderPage() {
  const location = useLocation()
  const key = location.pathname.split('/')[1] || 'empresa'
  const config = moduleData[key]
  if (!config) return <section className="empty-page"><span className="eyebrow">MÓDULO MATRIXFLOW</span><h1>{labels[key] || 'Página no encontrada'}</h1><p>El módulo todavía no está disponible.</p></section>
  return <ModulePage config={config} />
}

function ModulePage({ config }: { config: ModuleConfig }) {
  const [rows, setRows] = useState<Row[]>(config.rows)
  const [editing, setEditing] = useState<Row | null>(null)
  const [query, setQuery] = useState('')
  const filteredRows = rows.filter((row) => Object.values(row).some((value) => value.toLowerCase().includes(query.toLowerCase())))

  const saveRow = () => {
    if (!editing) return
    if (editing.id) setRows((current) => current.map((row) => row.id === editing.id ? editing : row))
    else setRows((current) => [...current, { ...editing, id: String(Date.now()) }])
    setEditing(null)
  }

  const removeRow = (id: string) => setRows((current) => current.filter((row) => row.id !== id))
  const startNew = () => setEditing(Object.fromEntries(config.columns.map((column) => [column.key, ''])))

  return <section className="module-page">
    <div className="module-heading"><div><div className="breadcrumb-line"><span>Inicio</span><span>/</span><b>{config.title}</b></div><h1>{config.title}</h1><p>{config.description}</p></div><button className="module-primary" onClick={startNew}>＋ Nueva {config.singular}</button></div>
    {config.metrics && <div className="module-metrics">{config.metrics.map((metric) => <div className="module-metric" key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong></div>)}</div>}
    <div className="module-toolbar"><div className="module-count"><strong>{rows.length}</strong> registros simulados</div><div className="module-actions"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Buscar ${config.title.toLowerCase()}...`} aria-label={`Buscar ${config.title}`} /><button className="module-export">↓ Exportar</button></div></div>
    <div className="module-card"><div className="module-table-wrap"><table className="module-table"><thead><tr>{config.columns.map((column) => <th key={column.key}>{column.label}</th>)}<th className="actions-column">Acciones</th></tr></thead><tbody>{filteredRows.map((row) => <tr key={row.id}>{config.columns.map((column) => <td key={column.key}>{column.key === 'status' ? <span className={`module-status ${statusClass(row[column.key])}`}>{row[column.key]}</span> : row[column.key]}</td>)}<td className="row-actions"><button onClick={() => setEditing({ ...row })} aria-label={`Editar ${config.singular}`}>✎</button><button onClick={() => removeRow(row.id)} aria-label={`Eliminar ${config.singular}`}>⌫</button></td></tr>)}</tbody></table>{filteredRows.length === 0 && <div className="module-empty">No hay registros que coincidan con la búsqueda.</div>}</div><div className="module-card-footer">Mostrando {filteredRows.length} de {rows.length} registros <span>Datos simulados · listos para conectar con la API</span></div></div>
    {editing && <div className="module-form-card"><div className="module-form-heading"><div><span className="eyebrow">CRUD LOCAL</span><h2>{editing.id ? `Editar ${config.singular}` : `Nueva ${config.singular}`}</h2></div><button onClick={() => setEditing(null)} aria-label="Cerrar formulario">×</button></div><div className="module-form-grid">{config.columns.map((column) => <label key={column.key}>{column.label}<input value={editing[column.key] || ''} onChange={(event) => setEditing({ ...editing, [column.key]: event.target.value })} /></label>)}</div><div className="module-form-actions"><button className="module-cancel" onClick={() => setEditing(null)}>Cancelar</button><button className="module-primary" onClick={saveRow}>Guardar registro</button></div></div>}
  </section>
}
